FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

RUN bun install 
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

COPY ./apps/backend ./apps/backend
COPY ./packages/db  ./packages/db

EXPOSE 3000

CMD ["bun","run","start:web"]