name: Deploy the ws to server
on: 
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to deployment
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker loging
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: abhibr/monorepo-docker-deployment-ws:${{github.sha}}

      - name: Execute ssh cmnds using password
        uses: appleboy/ssh-action@v1.2.0
        with:
            host: 52.66.243.177
            username: ubuntu
            key: ${{secrets.SSH_PRIVATE_KEY}}
            port: 22
            script: |
                sudo docker pull abhibr/monorepo-docker-deployment-ws:${{github.sha}}
                sudo docker stop monorepo-ws || true
                sudo docker rm monorepo-ws || true
                sudo docker run --name monorepo-ws -d -p 8081:8081 abhibr/monorepo-docker-deployment-ws:${{github.sha}}
                sudo docker image prune -a -f